### ISSUE TITLE
run "python tests.py" error

### ISSUE THREAD

**Issue by 4781121** [Congyuwang/AlphaNetV3#27]
======================================================================
ERROR: test_save_model (__main__.TestAlphaNetV2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\AlphaNetV3\tests\tests.py", line 172, in test_save_model
    alpha_net.save("./.test_alpha_net_save/model")
  File "D:\base\path\py3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\base\path\py3\lib\site-packages\tensorflow\python\saved_model\function_serialization.py", line 27, in _serialize_function_spec
    raise NotImplementedError(
NotImplementedError: Cannot serialize a method function without a named 'self' argument.

======================================================================
ERROR: test_save_model (__main__.TestAlphaNetV3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\AlphaNetV3\tests\tests.py", line 240, in test_save_model
    alpha_net_v3.save("./.test_alpha_net_save/model")
  File "D:\base\path\py3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\base\path\py3\lib\site-packages\tensorflow\python\saved_model\function_serialization.py", line 27, in _serialize_function_spec
    raise NotImplementedError(
NotImplementedError: Cannot serialize a method function without a named 'self' argument.

======================================================================
ERROR: test_save_model (__main__.TestAlphaNetV4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\AlphaNetV3\tests\tests.py", line 308, in test_save_model
    alpha_net_v4.save("./.test_alpha_net_save/model")
  File "D:\base\path\py3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\base\path\py3\lib\site-packages\tensorflow\python\saved_model\function_serialization.py", line 27, in _serialize_function_spec
    raise NotImplementedError(
NotImplementedError: Cannot serialize a method function without a named 'self' argument.

======================================================================
FAIL: test_last_batch_of_training_dataset (__main__.TestDataNormalizationModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\AlphaNetV3\tests\tests.py", line 504, in test_last_batch_of_training_dataset
    self.assertTrue(__is_all_close__(
AssertionError: False is not true : last batch of training data (start 20116595): failure

----------------------------------------------------------------------
Ran 31 tests in 64.568s

FAILED (failures=1, errors=3)

===========================
python 3.9
torch                        1.12.1
tensorflow                   2.9.2
Pillow                       9.2.0
pandas                       1.4.4
numpy                        1.23.2
numba                        0.56.2
keras                        2.9.0

**Comment by ZM-J** [comment]
So how did you solve this?
